# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/myip_v1_0_bfm_1/myip_v1_0_bfm_1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myip_v1_0_bfm_1 || ORIG_REF_NAME==myip_v1_0_bfm_1} -quiet] -quiet

# IP: bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_myip_0_0/myip_v1_0_bfm_1_myip_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myip_v1_0_bfm_1_myip_0_0 || ORIG_REF_NAME==myip_v1_0_bfm_1_myip_0_0} -quiet] -quiet

# IP: bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==myip_v1_0_bfm_1_master_0_0 || ORIG_REF_NAME==myip_v1_0_bfm_1_master_0_0} -quiet] -quiet

# XDC: bd/myip_v1_0_bfm_1/myip_v1_0_bfm_1_ooc.xdc
