# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/University/TERM_7/FPGA/project/IP/IP2/IP2.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'myip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/TERM_7/FPGA/project/IP/IP2/IP2.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/University/TERM_7/FPGA/project/IP/IP2/IP2.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0.xci
# IP: The module: 'myip_v1_0_bfm_1_master_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/University/TERM_7/FPGA/project/IP/IP2/IP2.srcs/sources_1/bd/myip_v1_0_bfm_1/ip/myip_v1_0_bfm_1_master_0_0/myip_v1_0_bfm_1_master_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'myip_v1_0_bfm_1_master_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
